spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_api
    username: dev
    password: dev123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    # locations: classpath:db/migration # If necessary.
    baseline-on-migrate: true
    baseline-version: 1