spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_api
    username: dev
    password: dev123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true